source:      .
destination: /tmp/wallrazer.com/_site
includes:    ./_includes

url: http://wallrazer.com

auto: false
exclude:
- fabfile.py
- build
- README.markdown
- post_update.sh
- mig.yaml

rdiscount:
    extensions: [smart, autolink]