source:      .
destination: ./_site
includes:    ./_includes

url: http://wallrazer.com

auto: false
exclude:
- fabfile.py
- build
- README.markdown
- post_update.sh

rdiscount:
    extensions: [smart, autolink]